# Generated by Django 3.2.15 on 2022-10-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221016_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
    ]
