# Generated by Django 3.2.15 on 2022-11-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20221127_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
    ]
